[target.aarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture arm64 || true",
  "apt-get update",
  "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends perl pkg-config make clang libssl-dev:arm64"
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = ["PKG_CONFIG_ALLOW_CROSS"]

[target.aarch64-linux-android]
pre-build = [
  "apt-get update",
  "DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends perl pkg-config make clang"
]

[target.aarch64-linux-android.env]
passthrough = ["PKG_CONFIG_ALLOW_CROSS", "OPENSSL_NO_PKG_CONFIG", "OPENSSL_STATIC"]

[target.x86_64-unknown-freebsd.env]
passthrough = ["PKG_CONFIG_ALLOW_CROSS", "OPENSSL_NO_PKG_CONFIG", "OPENSSL_STATIC"]

[target.x86_64-unknown-illumos.env]
passthrough = ["PKG_CONFIG_ALLOW_CROSS", "OPENSSL_NO_PKG_CONFIG", "OPENSSL_STATIC"]
